# Generated by Django 4.2 on 2024-01-03 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Talaba',
        ),
    ]
